version: '2'

services:
  web:
    build: .
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_web
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/home/www/test_web
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    container_name: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: